// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG39aULDFhHq9NY9K0X7ZoaW_uYQp6k5E',
    appId: '1:669753535346:web:c063841b0ee28417948beb',
    messagingSenderId: '669753535346',
    projectId: 'flutter-masterclass-66f6c',
    authDomain: 'flutter-masterclass-66f6c.firebaseapp.com',
    storageBucket: 'flutter-masterclass-66f6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGB7jJpcBhf8jipRHEgseMeT0G0yiNw-8',
    appId: '1:669753535346:android:30ee4c38d95e3645948beb',
    messagingSenderId: '669753535346',
    projectId: 'flutter-masterclass-66f6c',
    storageBucket: 'flutter-masterclass-66f6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoAqSAg-opKANydQzdFER14_97oDMG6yA',
    appId: '1:669753535346:ios:0e33e501c66ad7f6948beb',
    messagingSenderId: '669753535346',
    projectId: 'flutter-masterclass-66f6c',
    storageBucket: 'flutter-masterclass-66f6c.appspot.com',
    iosBundleId: 'com.example.flutterRpg',
  );

}